baseURL: "https://felipevaldez.com" 
title: Felipe Valdez Gómez de la Torre
paginate: 20
theme: PaperMod

defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Publications
          url: publications/
          weight: 1
        - name: Mapping Projects
          url: projects/
          weight: 2
        - name: Tutorials
          url: tutorials/
          weight: 3
        - name: Tags
          url: tags/
          weight: 4
    params:
      profileMode:
        enabled: true
      socialIcons:
          - name: Email
            url: mailto:felipemiguelvaldez@gmail.com
          - name: CV
            url: cv.pdf
          - name: Google Scholar
            url: https://scholar.google.com/citations?user=VC2gTN0AAAAJ&hl=en
          - name: ORCID
            url: https://orcid.org/0000-0001-6999-5657
          - name: linkedin
            url: https://www.linkedin.com/in/felipevaldez/
          - name: GitHub
            url: https://github.com/fmvaldezg
          - name: Location
            url: location/
          #- name: Office Hours
          #  url: officehours/

          #- name: YouTube
          #  url: https://www.youtube.com/@alexandermccallsmithoffici9000
          #- name: Twitter
          #  url: https://twitter.com/McCallSmith
  
  es:
    languageName: "Español"
    contentDir: "content/es"
    weight: 2 
    menu:
      main:
        - name: Publicaciones
          url: publications/
          weight: 1
        - name: Proyectos de Mapeo y SIG
          url: projects/
          weight: 2
        - name: Tutoriales
          url: tutorials/
          weight: 3
        - name: Tags
          url: tags/
          weight: 4
    params:
      profileMode:
        enabled: true
        title: "Felipe Valdez, Ph.D."
        subtitle: "Soy un Geógrafo especializado en geografía urbana y económica, con un profundo compromiso por aprovechar la cartografía, los SIG y el análisis de datos para fomentar el desarrollo comunitario y promover una sociedad más justa.<br><br>Con más de una década de experiencia en academia e investigación aplicada, estoy dedicado a avanzar la educación geográfica y promover el uso de tecnologías espaciales para abordar inequidades sociales y ambientales.<br><br>En mi rol actual como Especialista en SIG en Temple University, colaboro en proyectos que integran experiencia técnica con el empoderamiento comunitario.<br><br>Mi investigación y enseñanza se centra en SIG participativo, desigualdad espacial y en el uso de herramientas geográficas para involucrar a las comunidades en la co-creación de soluciones a desafíos urbanos.<br><br>Mi trayectoria académica incluye un Doctorado en Geografía de Northern Illinois University, donde investigué las dinámicas espaciales de precios de vivienda, preferencias residenciales y segregación en Quito, Ecuador. También poseo una maestría en Geografía de Países en Desarrollo de la Université Paris 1 Panthéon-Sorbonne, donde exploré el desarrollo periférico urbano, así como una maestría en Planificación Urbana y Desarrollo Regional de la Pontificia Universidad Católica del Ecuador.<br><br>Me apasiona crear alianzas significativas y utilizar el análisis geográfico para construir entornos urbanos más inclusivos y equitativos.<br><br>¡Conectemos para discutir oportunidades de colaboración!"
        imageUrl: "picture.jpg"
        imageWidth: 160
        imageHeight: 160
        imageTitle: Felipe Valdez
        buttons:
          - name: Publicaciones
            url: publications/
            weight: 1
          - name: Proyectos de Mapeo
            url: projects/
            weight: 2
          - name: Tutoriales
            url: tutorials/
            weight: 3
          - name: Tags
            url: tags/
            weight: 4
      socialIcons:
          - name: Email
            url: mailto:felipemiguelvaldez@gmail.com
          - name: CV
            url: cv_es.pdf
          - name: Google Scholar
            url: https://scholar.google.com/citations?user=VC2gTN0AAAAJ&hl=en
          - name: ORCID
            url: https://orcid.org/0000-0001-6999-5657
          - name: linkedin
            url: https://www.linkedin.com/in/felipevaldez/
          - name: GitHub
            url: https://github.com/fmvaldezg
          - name: Location
            url: location/

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

params:
    description: "Intercultural urban and economic geographer with more than 12 years of experience in higher education and research. Applying GIS to urban solutions based on collective action."
    author: Felipe Valdez Gómez de la Torre
    displayFullLangName: true
    googleAnalyticsID: "G-RC52W8J799"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Felipe Valdez, Ph.D.
          subtitle: "I am a Geographer specializing in urban and economic geography, with a deep commitment to leveraging mapping, GIS, and data analysis to foster community development and promote a more just society.<br><br>With over a decade of experience in academia and applied research, I am committed to advancing geographic education and promoting the use of spatial technologies to address social and environmental inequities.<br><br>In my current role as a GIS Specialist at Temple University, I collaborate on projects that integrate technical expertise with community empowerment.<br><br>My research and teaching focuses on participatory GIS, spatial inequality, and using geographic tools to engage communities in co-creating solutions to urban challenges.<br><br>My academic journey includes a Ph.D. in Geography from Northern Illinois University, where I investigated the spatial dynamics of housing prices, residential preferences, and segregation in Quito, Ecuador. I also hold a master's degree in Geography of Developing Countries from Université Paris 1 Panthéon-Sorbonne, where I explored urban peripheral development, as well as a master's degree in Urban Planning and Regional Development from Pontificia Universidad Católica del Ecuador.<br><br>I am passionate about creating meaningful partnerships and using geographic analysis to build more inclusive and equitable urban environments.<br><br>Let's connect to discuss opportunities for collaboration and impact!"
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Felipe Valdez
          buttons:
            - name: Publications
              url: publications/
            - name: Tutorials
              url: tutorials/
            - name: Mapping Projects
              url: projects/
            #- name: Data
            #  url: data/
            - name: Tags
              url: tags/
            #- name: Archive
            #  url: archive/
            #- name: Blog
            #  url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)



    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Felipe Valdez Gómez de la Torre"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
